server:
    port: 8773

# H2
spring:
    h2:
        console:
            enabled: true
            path: /h2
# Datasource
    datasource:
        url: jdbc:h2:file:~/test
        username: sa
        password: 
        driver-class-name: org.h2.Driver

        
payroll:
    server:
        baseUri: http://dummy.restapiexample.com/api/v1/