spring:
    datasource:
        url: jdbc:mysql://localhost:3306/microapp?useSSL=false
        username: root
        password: system
    jpa:
        hibernate:
            ddl-auto: create
        database-platform: org.hibernate.dialect.MySQL57Dialect
        generate-ddl: true
        show-sql: true